### PR TITLE
fix: do not create user mappings in SELECT mode

### LINKED ISSUE #44: add option to disable selection mode mappings
It rly annoys me that this plugin creates mappings for selection mode.
When I use plugins with placeholders and wanna write sth with `s`it won't work

### PR DESCRIPTION
**Pull request by Daxtorim**
Closes #44

### CODE REVIEW

File: lua/surround/init.lua [hunk 1]
```diff
@@ -566,57 +567,52 @@ function M.set_keymaps()
 		end
 	end
 
+	-- vim will only set '< and '> marks when using gv to re-select last visual selection
+	map("v", "<Plug>SurroundAddVisual",        "<esc>gv<cmd>lua require('surround').surround_add(false, false)<cr>")
```
Comment (Daxtorim) [inline lua/surround/init.lua:571]: This one is intentionally still using `v` mode (`VISUAL` *and* `SELECT`) so that people can still create their own `SELECT` mappings with this Plug command.
